= Guided Exercises
include::_attributes.adoc[]

== Security


[#authentication]
=== Authentication
To access Datagrid clusters, you can use either credentials generated by default or add your own.
By default, the Datagrid operator generates base64-encoded credentials for the user (infinispan-generated-secret) and for the operator itself to manage Datagrid resources (infinispan-generated-operator-secret).
You can retrieve these credentials easily.
----
oc get secret infinispan-generated-secret
oc get secret infinispan-generated-secret -o jsonpath="{.data.identities\.yaml}" | base64 --decode
----

To add your own credentials, you can create an identities.yaml with the credentials you want to add.
----
credentials:
- username: myfirstusername
  password: changeme-one
- username: mysecondusername
  password: changeme-two
----
Now, create the authentication secret for these credentials.
----
oc create secret generic --from-file=identities.yaml connect-secret
----
And finally, 


* Authorization

== Resources

* Replicas, Memory, CPU and JVM arguments.

== Encryption

* Using OCP TLS certificates or using custom TLS certificates.

== Cross-site replication

* Cross-site replication in your own cluster.
